version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
   test:
     description: Setup and run application tests
     executor:
       name: windows/default
     steps:
       - checkout
       - restore_cache:
           keys:
             - dotnet-packages-v1-{{ checksum "TattleTrail/TattleTrail.Test/TattleTrail.Test.csproj" }}
       - run:
           name: "Install project dependencies"
           command: dotnet.exe restore "TattleTrail/TattleTrail.Test/TattleTrail.Test.csproj"
       - save_cache:
           paths:
             - C:\Users\circleci\.nuget\packages
           key: dotnet-packages-v1-{{ checksum ""TattleTrail/TattleTrail.Test/TattleTrail.Test.csproj"" }}
       - run:
           name: "Run Application Tests"
           command: dotnet.exe test -v n --results-directory:test_coverage --collect:"Code Coverage"
       - run:
           name: "Print Working Directory"
           command: pwd
       - store_artifacts:
           path: C:\Users\circleci\project\test_coverage
build:
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "TattleTrail/TattleTrail/TattleTrail.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore "TattleTrail/TattleTrail/TattleTrail.csproj"
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "TattleTrail/TattleTrail/TattleTrail.csproj" }}
      - run:
          name: "Run Build step"
          command: dotnet.exe publish "TattleTrail/TattleTrail/TattleTrail.csproj" -c Release -r win10-x64

workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test