version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "TattleTrail/TattleTrail/TattleTrail.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore "TattleTrail/TattleTrail/TattleTrail.csproj"
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "TattleTrail/TattleTrail/TattleTrail.csproj" }}
      - run:
          name: "Run Build step"
          command: dotnet.exe publish "TattleTrail/TattleTrail/TattleTrail.csproj" -c Release -r win10-x64