version: '3.4'

networks:
  app-tier:
    driver: bridge

services:
  tattletrail:
    image: ${DOCKER_REGISTRY-}tattletrail
    build:
      context: TattleTrail/
      dockerfile: Dockerfile
    environment:
      - RELEASE
    env_file:
      - default.env
    depends_on:
      - db
    container_name: tattletrail
    networks:
      - app-tier
  db:
    image: 'bitnami/redis:latest'
    container_name: redis-image
    ports:
      - "6379:6379"
    networks:
      - app-tier