version: '3.4'

services:
  tattletrail:
    image: ${DOCKER_REGISTRY-}tattletrail
    build:
      context: TattleTrail/
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    depends_on:
      - db
    container_name: TattleTrailv1.0
  db:
    image: redis
    container_name: redis-image